# Changes here will be overwritten by Copier
_commit: 2d0c192
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: true
email: OpenSource@point72.com
github: Point72
project_description: ccflow is a collection of tools for workflow configuration, orchestration,
    and dependency injection
project_name: ccflow
python_version_primary: '3.9'
team: Point72, L.P.
