# NOTE: This file will be removed
# before open sourcing

package:
  name: ccflow
  version: 0.2.2

source:
  path: ..

build:
  script:
    - {{ PYTHON }} -m pip install --no-deps --no-build-isolation --ignore-installed -vvv .
  noarch: python

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - cloudpathlib
    - cloudpickle
    - dask
    - hydra-core
    - IPython
    - jinja2
    - numpy<2
    - orjson
    - pandas
    - pyarrow
    - pydantic >=2.6,<3
    - smart_open
    - tenacity

test:
  imports:
    - ccflow

about:
  home: TODO
  summary: TODO
  license: PROPRIETARY
  license_family: PROPRIETARY
