name: Build Status

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - LICENSE
      - README.md
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]  # NOTE: use macos-13 as no standard csp wheels for arm64 3.9
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v5

    - uses: actions-ext/python/setup@main
      with:
        version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: make develop

    - name: Lint
      run: make lint

    - name: Checks
      run: make checks

    - name: Build
      run: make build

    - name: Test
      run: make coverage

    - name: Upload test results (Python)
      uses: actions/upload-artifact@v4
      with:
        name: py-test-results-${{ matrix.os }}-${{ matrix.python-version }}-
        path: junit.xml
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: '**/junit.xml'
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      if: matrix.os == 'ubuntu-latest'

    - name: Twine check
      run: make dist

    - uses: actions/upload-artifact@v4
      with:
        name: dist-${{matrix.os}}
        path: dist
      if: matrix.os == 'ubuntu-latest'
